HaberSitem.Web/Controllers/ChildViewsController.cs
using HaberSitem.Business;
using HaberSitem.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HaberSitem.Web.Controllers
{
    public class ChildViewsController : Controller
    {
        [ChildActionOnly]
        public ActionResult Navbar()
        {
            KategorilerBusiness busiKategoriler = new KategorilerBusiness();
            List<Kategoriler> kategoriler = busiKategoriler.HepsiniGetir();

            return PartialView(kategoriler);
        }
    }
}

HaberSitem.Web/Controllers/HomeController.cs
using HaberSitem.Business;
using HaberSitem.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HaberSitem.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Erişim Sağlandı";

            return View();
        }

        KategorilerBusiness busiKategori;

        [HttpPost]
        public ActionResult Deneme()
        {
            busiKategori = new KategorilerBusiness();
            List<Kategoriler> kategoriler = busiKategori.HepsiniGetir();
            return RedirectToAction("Index");
        }
    }
}

HaberSitem.Web/Views/ChildViews/Navbar.cshtml
@model List<HaberSitem.Entity.Kategoriler>

@foreach (var item in Model)
{
    <li class="nav-item"> <a class="nav-link" href="#">@item.KategoriAdi</a> </li>
}

HaberSitem.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HaberSitem.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HaberSitem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>River Bootstrap 4 Template by Grafreez</title>

    <!--Bootstrap core CSS-->
    <link href="/Content/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Custom styles for this template -->

    <link href="/Content/css/custom.css" rel="stylesheet">
    <link href="/Content/css/responsive-style.css" rel="stylesheet">
    <link href="/Content/css/weather-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/Content/css/font-awesome.min.css" />
    <link href="/Content/css/lightbox.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/Content/css/loaders.css" />
    <style></style>
</head>

<body>
    <div class="loader loader-bg">
        <div class="loader-inner ball-pulse-rise">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <header>
        <div class="small-top">
            <div class="container">
                    <div class="col-lg-4 date-sec hidden-sm-down">
                        <div id="Date"></div>
                    </div>
                        <div class="social-icon"> <a target="_blank" href="#" class=" fa fa-facebook"></a> <a target="_blank" href="#" class=" fa fa-twitter"></a> <a target="_blank" href="#" class=" fa fa-google-plus"></a> <a target="_blank" href="#" class=" fa fa-linkedin"></a> <a target="_blank" href="#" class=" fa fa-youtube"></a> <a target="_blank" href="#" class=" fa fa-vimeo-square"></a> </div>
                    
            </div>
        </div>
        <div class="top-head">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-lg-4 left">
                        <h1>Grafreez News<small>Get the latest News</small></h1>
                    </div>
                    <div class="col-md-6 col-lg-5 offset-lg-3 admin-bar hidden-sm-down">
                        <nav class="nav nav-inline"> 
                            <a href="#" class="nav-link">
                                <span class="ping"></span>
                                <i class="fa fa-envelope-o"></i>
                            </a> <a href="#" class="nav-link">
                            <i class="fa fa-bell-o"></i></a> 
                            <a href="#" class="nav-link">Bruce Wayne 
                                <img class="img-fluid img-circle" src="/Content/img/admin-bg.jpg">
                            </a> 
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <nav class="navbar top-nav navbar-toggleable-md">
        <div class="container">
            <button class="navbar-toggler hidden-lg-up " type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation"> &#9776; </button>
            <div class="collapse navbar-collapse" id="exCollapsingNavbar2">
                <ul class="navbar-nav mr-auto">
                    @Html.Action("Navbar","ChildViews")
                </ul>
                <form class="pull-xs-right">
                    <div class="search">
                        <input type="text" class="form-control" maxlength="64" placeholder="Search" />
                        <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </nav>
    @RenderBody()
    <div class="sub-footer">
        <div class="container">
            <h3>
                <div class="heading-large">Top Five Stories</div>
            </h3>
            <div id="myCarousel" class="carousel slide" data-ride="carousel">

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="img-fluid" src="/Content/img/NoImage.png">
                        <div class="carousel-caption">
                            <div class="news-title">
                                <h2 class=" title-large"><a href="#">Ray madison may struggle to get best from Paul in a 4-2-3-1 formation</a></h2>
                            </div>
                        </div>
                    </div>
                    <!-- End Item -->

                    <div class="carousel-item">
                        <img class="img-fluid" src="/Content/img/NoImage.png">
                        <div class="carousel-caption">
                            <div class="news-title">
                                <h2 class=" title-large"><a href="#">Delta passengers got pizza delivered to the plane</a></h2>
                            </div>
                        </div>
                    </div>
                    <!-- End Item -->

                    <div class="carousel-item">
                        <img class="img-fluid" src="/Content/img/NoImage.png">
                        <div class="carousel-caption">
                            <div class="news-title">
                                <h2 class=" title-large"><a href="#">Key Republican Senator Says She Will Not Vote for former president!</a></h2>
                            </div>
                        </div>
                    </div>
                    <!-- End Item -->

                    <div class="carousel-item">
                        <img class="img-fluid" src="/Content/img/NoImage.png">
                        <div class="carousel-caption">
                            <div class="news-title">
                                <h2 class=" title-large"><a href="#">An Alternative Form of Mental Health Care Gains a Foothold</a></h2>
                            </div>
                        </div>
                    </div>
                    <!-- End Item -->

                    <div class="carousel-item">
                        <img class="img-fluid" src="/Content/img/NoImage.png">
                        <div class="carousel-caption">
                            <div class="news-title">
                                <h2 class=" title-large"><a href="#">Woman dies in prison drone police chase </a></h2>
                            </div>
                        </div>
                    </div>
                    <!-- End Item -->

                </div>
                <!-- End Carousel Inner -->

                <ul class="list-group col-sm-4">
                    <li data-target="#myCarousel" data-slide-to="0" class="list-group-item active">
                        <h4>Ray madison may struggle to get best from Paul in a 4-2-3-1 formation</h4>
                    </li>
                    <li data-target="#myCarousel" data-slide-to="1" class="list-group-item">
                        <h4>Delta passengers got pizza delivered to the plane</h4>
                    </li>
                    <li data-target="#myCarousel" data-slide-to="2" class="list-group-item">
                        <h4>Key Republican Senator Says She Will Not Vote for former president!</h4>
                    </li>
                    <li data-target="#myCarousel" data-slide-to="3" class="list-group-item">
                        <h4>An Alternative Form of Mental Health Care Gains a Foothold</h4>
                    </li>
                    <li data-target="#myCarousel" data-slide-to="4" class="list-group-item">
                        <h4>Woman dies in prison drone police chase </h4>
                    </li>
                </ul>

                <!-- Controls -->
                <div class="carousel-controls"> <a class="left carousel-control" href="#myCarousel" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left"></span> </a> <a class="right carousel-control" href="#myCarousel" data-slide="next"> <span class="glyphicon glyphicon-chevron-right"></span> </a> </div>
            </div>
            <!-- End Carousel -->
        </div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12">
                    <h6 class="heading-footer">ABOUT US</h6>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</p>
                    <p><i class="fa fa-phone"></i> <span>Call Us :</span> +91 9999 878 398</p>
                    <p><i class="fa fa-envelope"></i> <span>Send Email :</span> info@webenlance.com</p>
                </div>
                <div class="col-lg-2 col-md-4">
                    <h6 class="heading-footer">QUICK LINKS</h6>
                    <ul class="footer-ul">
                        <li><a href="#"> Career</a></li>
                        <li><a href="#"> Privacy Policy</a></li>
                        <li><a href="#"> Terms & Conditions</a></li>
                        <li><a href="#"> Client Gateway</a></li>
                        <li><a href="#"> Ranking</a></li>
                        <li><a href="#"> Case Studies</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-4">
                    <h6 class="heading-footer">LATEST NEWS</h6>
                    <div class="post">
                        <p>Key Republicans sign letter warning against candidate<span>August 3,2015</span></p>
                        <p>Obamacare Appears to Be Making People Healthie <span>August 3,2015</span></p>
                        <p>Syria war: Why the battle for Aleppo matters<span>August 3,2015</span></p>
                    </div>
                </div>
                <div class="col-lg-2 col-md-4 social-icons">
                    <h6 class="heading-footer">FOLLOW</h6>
                    <ul class="footer-ul">
                        <li><a href="#"><i class=" fa fa-facebook"></i> Facebook</a></li>
                        <li><a href="#"><i class=" fa fa-twitter"></i> Twitter</a></li>
                        <li><a href="#"><i class=" fa fa-google-plus"></i> Google+</a></li>
                        <li><a href="#"><i class=" fa fa-linkedin"></i> Linkedin</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!--footer start from here-->

    <div class="copyright">
        <div class="container">
            <div class="col-lg-6 col-md-4">
                <p>© 2016 - <a href="http://grafreez.com">Grafreez.com</a></p>
            </div>
            <div class="col-lg-6 col-md-8">
                <ul class="bottom_ul">
                    <li><a href="#">About us</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Faq's</a></li>
                    <li><a href="#">Contact us</a></li>
                    <li><a href="#">Site Map</a></li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
        ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/Content/js/jquery.min.js"></script>
    <script src="/Content/js/bootstrap.min.js"></script>
    <script src="/Content/js/core.js"></script>
    <script src="/Content/js/lightbox-plus-jquery.min.js"></script>

</body>
</html>